GET http://localhost:4300/todo
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ0ZXN0MTAxMiI6InRlc3QxMDEyIn0.eCCzg8mmvbVcVy3JhGBXEDgqf48ZwzK-_aA8DEMgrfY

###
POST http://localhost:4300/user/register
Content-Type: application/json

{
  "username": "test1002",
  "password": "test1002",
  "email": "email"
}

###

GET http://localhost:4300/user/618540f2a2040110cc63c813
Accept: application/json

###
POST http://localhost:4300/user/login
Content-Type: application/x-www-form-urlencoded

username=test1012&password=test1012


###
GET http://localhost:4300/user?page=1&page_size=10
Accept: application/json

<> 2021-10-31T190457.200.txt

###
PUT http://localhost:4300/user/6180d2a3f41928f611903b2a
Content-Type: application/json

{
  "username": "111admin",
  "password": "admin12345",
  "email": "844922881@qq.com"
}

